//@baseUrl = https://cse341-z0l7.onrender.com

@baseUrl = http://localhost:8080

### Get All Contacts
GET {{baseUrl}}/contacts

### Get a Single Contact by ID
GET {{baseUrl}}/contacts/67283240a034ccf020dceb46

### Create a New Contact
POST {{baseUrl}}/contacts
Content-Type: application/json

{
    "firstName": "Matt",
    "lastName": "Felber",
    "email": "m@example.com",
    "favoriteColor": "blue",
    "birthday": "1996-96-96"
}

### Update an Existing Contact
PUT {{baseUrl}}/contacts/6739418995d279b076229adc
Content-Type: application/json

{
    "favoriteColor": "Purple"
}

### Delete a Contact
DELETE {{baseUrl}}/contacts/6739418995d279b076229adc
